# Generated by Django 3.0.7 on 2020-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20200615_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFieldJavascript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=30)),
            ],
        ),
    ]
